In [1]:
import pandas as pd
grade = pd.Series([88,77,90,45,66])
grade

0    88
1    77
2    90
3    45
4    66
dtype: int64

In [6]:
print(grade.mean())

73.2

In [7]:
print(grade.max())

90

In [ ]:
# Pandas DataFrame

In [10]:
data = {
    "Names":["Alice","Bob","Charlie"],
    "Ages":[24,56,33],
    "City":["Chicago","Berkeley","LA"]
}

In [11]:
data.keys()

dict_keys(['Names', 'Ages', 'City'])

In [17]:
data.values()

dict_values([['Alice', 'Bob', 'Charlie'], [24, 56, 33], ['Chicago', 'Berkeley', 'LA']])

In [18]:
data["Names"]

['Alice', 'Bob', 'Charlie']

In [14]:
df = pd.DataFrame(data)
df

     Names  Ages      City
0    Alice    24   Chicago
1      Bob    56  Berkeley
2  Charlie    33        LA

In [19]:
# Access Column
df['Names']

0      Alice
1        Bob
2    Charlie
Name: Names, dtype: str

In [21]:
# Access Multiple Columns
df[['Names','City']]

     Names      City
0    Alice   Chicago
1      Bob  Berkeley
2  Charlie        LA

In [24]:
# Filter
df[df['Ages']>30]

     Names  Ages      City
1      Bob    56  Berkeley
2  Charlie    33        LA

In [25]:
df[df['City'] == 'Berkeley']

  Names  Ages      City
1   Bob    56  Berkeley

In [43]:
# Update Column
df['Ages'] = df['Ages']+1
df

     Names  Ages      City
0    Alice    25   Chicago
1      Bob    57  Berkeley
2  Charlie    34        LA

In [45]:
# Add data (create column)
df ['Senior'] = df['Ages']> 30
df

     Names  Ages      City  Senior
0    Alice    25   Chicago   False
1      Bob    57  Berkeley    True
2  Charlie    34        LA    True

In [46]:
# .loc and .iloc

df.loc[0]

Names       Alice
Ages           25
City      Chicago
Senior      False
Name: 0, dtype: object

In [47]:
df.loc[:,'City']

0     Chicago
1    Berkeley
2          LA
Name: City, dtype: str

In [50]:
df.iloc[1,2]

'Berkeley'